cetweb/cetweb/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template, redirect_to
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

#project
from cetweb.views import home

urlpatterns = patterns('',
    # Examples:
    #url(r'^$', direct_to_template, {"template":"splash.html"}, name='splash'),
    url(r'^$', home, name='home'),
    url(r'^home/', home, name='home'),
    url(r'^profiles/', include('profiles.urls')),
    url(r'^company/', include('company.urls')),
    url(r'^splash/', include('splash.urls')),
    url(r'^program/', include('program.urls')),
    url(r'^chatroom/', include('chatroom.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^info/', include('info.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/profile/$', redirect_to, {'url': '/profiles/dashboard/'}),
    url(r'^about/$', direct_to_template, {"template":"about.html"}, name='about'),
    url(r'^donate/$', direct_to_template, {"template":"donate.html"}, name='donate'),
    url(r'^faq/$', direct_to_template, {"template":"faq.html"}, name='faq'),
    url(r'^contact/$', direct_to_template, {"template":"contact.html"}, name='contact'),
    url(r'^globalprograms/$', direct_to_template, {"template":"globalprograms.html"}, name='about'),
    url(r'^apply/$', direct_to_template, {"template":"program/apply_reveal.html"}, name='apply'),
    url(r'^comments/', include('django.contrib.comments.urls')),

    # ERROR PAGES
    url(r'^construction/$', direct_to_template, {"template":"errors/construction.html"}, name='construction'),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cetweb/company/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template

urlpatterns = patterns('company.views',
	url(r'^$', 'company_list' , name='company_list'),
	url(r'^mentors/$', 'mentor_list' , name='mentor_list'),
	url(r'^investors/$', 'investor_list' , name='investor_list'),
    url(r'^profile/(?P<pk>[\w\d]+)/$', 'profile', name="company_profile"),
    url(r'^profile/create/$', 'create_company', name="company_create"),
    url(r'^profile/edit/(?P<pk>[\w\d]+)/$', 'edit_company', name="company_edit"),
    url(r'^job/listings/(?P<pk>[\w\d]+)/$', 'job_listing', name="job_listing"),
    url(r'^job/all/$', 'job_listing_list', name="job_listing_list"),
    url(r'^job/create/$', 'create_job', name="job_create"),
    url(r'^job/create/(?P<company_pk>[\w\d]+)/$', 'create_job', name="job_create"),
)

cetweb/info/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template

urlpatterns = patterns('info.views',
    url(r'^testimonial/create/$', 'testimonial_create', name="testimonial_create"),
)

cetweb/profiles/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template

urlpatterns = patterns('profiles.views',
    url(r'^signup/$', 'signup', name='signup'),
    url(r'^thanks/$', 'signup_helper'),

    url(r'^dashboard/$', 'dashboard',name='dashboard'),
)

cetweb/company/models.py
#standard model stuff
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin

class Milestone(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    date = models.DateField()
    def __unicode__(self):
        return self.title + " at " + str(self.date)
admin.site.register(Milestone)

class Company(models.Model):
    name = models.CharField(max_length=100)
    url = models.URLField()
    image = models.ImageField(upload_to="company_images",null=True,blank=True)
    pitch = models.TextField(default="",blank=True)
    video = models.URLField(null=True,blank=True,verbose_name="Video to pitch your idea")
    milestones = models.ManyToManyField(Milestone,blank=True)
    investors = models.CharField(max_length=500, blank=True)

    def __unicode__(self):
        return self.name
    @models.permalink
    def get_absolute_url(self):
        return ('company_profile', [self.pk])
admin.site.register(Company)

class Job(models.Model):
    title = models.CharField(max_length=100)
    company = models.ForeignKey(Company)
    requests = models.ManyToManyField(User,blank=True,verbose_name="People who are interested in the job.")

    available = models.BooleanField(default=True,verbose_name="Is this job still available?")
    description = models.TextField()

    def __unicode__(self):
        return str(self.company) + ": " + self.title
    @models.permalink
    def get_absolute_url(self):
        return ('job_listing', [self.pk])
admin.site.register(Job)

class Mentor(models.Model):
    name = models.CharField(max_length=100)
    url = models.URLField(null=True,blank=True)
    image = models.ImageField(upload_to="company_images",null=True,blank=True)
    email = models.EmailField()
    companies = models.ManyToManyField(Company,blank=True)
admin.site.register(Mentor)

class Investor(models.Model):
    name = models.CharField(max_length=100)
    url = models.URLField(null=True,blank=True)
    image = models.ImageField(upload_to="investor_images",null=True,blank=True)
    email = models.EmailField()
    companies = models.ManyToManyField(Company,blank=True)
admin.site.register(Investor)

cetweb/profiles/models.py
#standard model stuff
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin

#signals
from django.db.models.signals import post_save
from django.dispatch import receiver

from django.conf import settings
from company.models import Company


class Profile(models.Model):
    user = models.OneToOneField(User)
    stakeholder = models.CharField(max_length=50,choices=settings.STAKEHOLDERS,default=settings.STAKEHOLDER_DEFAULT)
    activated = models.BooleanField(default=False)

    #Founders:
    company = models.ForeignKey(Company,blank=True,null=True)
    role = models.CharField(max_length=50, blank=True,null=True)
    # Mentors:
    industries = models.CharField(max_length=50, blank=True,null=True)
    # Faculty:
    department = models.CharField(max_length=50, blank=True,null=True)

    def __unicode__(self):
        return self.user.last_name

@receiver(post_save,sender=User)
def create_user_profile(sender,instance,created,**kwargs):
    """
        Creates a Profile model for each User that is created.

        This function is called on the post_save signal from User.
    """
    if created:
        p = Profile.objects.create(user=instance)
admin.site.register(Profile)


# class Company(models.Model):
#     founders = models.ManyToManyField(User,blank=True)
#     name = models.CharField(primary_key=True)
#     url = models.URLField()
#     logo = models.ImageField()
#     created = models.DateField()
#     # milestones = models.CharField()
#     # investors = models.CharField()

cetweb/company/forms.py
from django.forms import ModelForm

from company.models import Company, Job

class CompanyForm(ModelForm):
    class Meta:
        model = Company

class JobForm(ModelForm):
    class Meta:
        model = Job 
        exclude = ('requests',)

cetweb/profiles/forms.py
from django import forms
from profiles.models import Profile
from django.contrib.auth.models import User

from django.forms import ModelForm

import random
import string

class ProfileForm(ModelForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=50)
    email = forms.EmailField()
    def save(self,commit=True):
        instance = super(ProfileForm,self).save(commit=commit)
        u = User()
        u.has_profile = True
        u.username = ''.join(random.choice(string.ascii_uppercase + string.digits) for x in range(20))
        u.first_name = self.cleaned_data['first_name']
        u.last_name = self.cleaned_data['last_name']
        u.email = self.cleaned_data['email']
        u.save()
        for p in Profile.objects.filter(user=u):
            p.delete()
        instance.user = u
        instance.save()
        return instance
    class Meta:
        model = Profile
        exclude = ("user","steakholder","activated")

cetweb/cetweb/views.py
#standard django stuff
from django.shortcuts import *
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

#project
from events.models import Event
from info.models import Testimonial

def home(request):
    """
        Displays the job listings.
    """
    context = {
        "events": Event.objects.all(),
        "testimonials": Testimonial.objects.all()
    }
    return render_to_response("home.html",context,context_instance=RequestContext(request))

cetweb/company/views.py
#standard django stuff
from django.shortcuts import *
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

#project
from company.models import Company, Job, Investor, Mentor
from company.forms import CompanyForm, JobForm

def profile(request,pk):
    """
        Displays a company profile page.
    """
    c = get_object_or_404(Company,pk=pk)
    return render_to_response("company/profile2.html",{"company":c},context_instance=RequestContext(request))

def job_listing(request,pk):
    """
        Displays a job listing.
    """
    j = get_object_or_404(Job,pk=pk)
    return render_to_response("company/job_listing.html",{"job":j},context_instance=RequestContext(request))

def job_listing_list(request):
    """
        Displays all job listings.
    """
    jobs = Job.objects.all()
    return render_to_response("company/job_listing_list.html",{"jobs":jobs},context_instance=RequestContext(request))

def company_list(request):
    """
        Displays all companies in the database
    """
    companies = Company.objects.all()
    return render_to_response("company/company_list.html",{"companies":companies},context_instance=RequestContext(request))

def investor_list(request):
    """
        Displays a list of all the investors.
    """
    investors = Investor.objects.all()
    return render_to_response("company/investor_list.html",{"investors":investors},context_instance=RequestContext(request))
def mentor_list(request):
    """
        Displays a list of all the mentors.
    """
    mentors = Mentor.objects.all()
    return render_to_response("company/mentor_list.html",{"mentors":mentors},context_instance=RequestContext(request))

#form views

#@login_required
def edit_company(request,pk):
    """
        Creates a company profile.
    """
    c = get_object_or_404(Company,pk=pk)
    form = CompanyForm(instance=c)
    if request.method == "POST":
        form = CompanyForm(request.POST,request.FILES,instance=c)
        if form.is_valid():
            company = form.save()
            return HttpResponseRedirect(reverse("company_profile",args=(company.pk,)))
    return render_to_response("company/company_form.html",{"form":form},context_instance=RequestContext(request))

@login_required
def create_company(request):
    """
        Creates a company profile.
    """
    form = CompanyForm()
    if request.method == "POST":
        form = CompanyForm(request.POST,request.FILES)
        if form.is_valid():
            company = form.save()
            return HttpResponseRedirect(reverse("company_profile",args=(company.pk,)))
    return render_to_response("company/company_form.html",{"form":form},context_instance=RequestContext(request))

@login_required
def create_job(request,company_pk=None):
    """
        Creates a job listing.
    """
    form = JobForm()
    
    if company_pk:
        company = get_object_or_404(Company,pk=company_pk)
        form.initial['company'] = company

    if request.method == "POST":
        form = JobForm(request.POST)
        if form.is_valid():
            #check that this person is a founder of the company
            if request.user not in form.instance.company.founders.all():
                messages.error(request,"Cannot create job listings for a company that you are not part of.")
                return render_to_response("company/job_form.html",{"form":form},context_instance=RequestContext(request))
            job = form.save()
            return HttpResponseRedirect(reverse("job_listing",args=(job.pk,)))
    return render_to_response("company/job_form.html",{"form":form},context_instance=RequestContext(request))

cetweb/profiles/views.py
from django.shortcuts import *
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import simplejson

from forms import ProfileForm
from company.models import Company, Mentor, Investor



# def signup(request):
#     if request.method == 'POST':
#         form = ProfileForm(request.POST)
#         if form.is_valid():
#             first_name = form.cleaned_data['first_name']
#             last_name = form.cleaned_data['last_name']
#             email = form.cleaned_data['email']
#             user = User.objects.create_user(first_name, last_name, email)
#             p = user.get_profile()
#             p.stakeholder = form.cleaned_data['stakeholder']
#             if p.stakeholder == "founder":
#                 p.startup_name = form.cleaned_data['startup_name'];
#                 p.startup_url = form.cleaned_data['startup_url'];
#                 p.role = form.cleaned_data['role']
#             elif p.stakeholder == "mentor":
#                 p.industries = form.cleaned_data['industries'];
#             elif p.stakeholder == "faculty":
#                 p.department = form.cleaned_data['department'];
#             p.save()
#             # return HttpResponseRedirect(reverse('/thanks'), {'first_name':first_name, 'last_name':last_name, email:'email'})
#     else:
#         form = ProfileForm() # An unbound form
#     return render_to_response('profiles/signup.html', {'form': form}, context_instance=RequestContext(request))



def signup_helper(request):
    results = {'success':False}
    if (request.method == 'POST'):
        POST = request.POST
        first_name = POST['first_name']
        last_name = POST['last_name']
        email = POST['email']
        user = User.objects.create_user(first_name, last_name, email)
        p = user.get_profile()
        p.stakeholder = POST['stakeholder']
        if p.stakeholder == "founder":
            name = POST['name'];
            url = POST['url'];
            p.role = POST['role']
            c = Company.objects.create(name=name, url=url)
            c.founders.add(p.user)
            p.company = c
        elif p.stakeholder == "mentor":
            p.industries = POST['industries'];
        elif p.stakeholder == "faculty":
            p.department = POST['department'];
        p.save()
        results['success'] = True
    json_results = simplejson.dumps(results)
    return HttpResponse(json_results, mimetype='application/json')


def signup(request):
    form = ProfileForm()
    print form
    if request.method=="POST":
        print request.POST
        form = ProfileForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("dashboard"))
        else:
            print form.errors
    return render_to_response('profiles/signup.html', {'form': form}, context_instance=RequestContext(request))


#@login_required
def dashboard(request):
    context = {
        "mentors": Mentor.objects.all(),
        "investors": Investor.objects.all(),
    }
    return render_to_response('profiles/dashboard.html', context, context_instance=RequestContext(request))

cetweb/cetweb/templates/company/company_form.html
{% extends "company/base.html" %}

{% block body %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" />
    </form>
{% endblock %}

cetweb/cetweb/templates/company/company_list.html
{% extends "company/base.html" %}

{% block body %}
	<div class="row">
		<div class="twelve columns centered">
			<h1 class="header-center" style="padding-top:40px;">CET Companies</h1>
			<p style="text-align:center;">These are some of the companies that came out of one of the CET programs in recent years.</p>
		</div>
	</div>
	<div class="row">
		<div style="margin-bottom:20px;" class="twelve columns">
			<hr/>
		    {% for company in companies %}
			    <div class="three columns">
	        	  	<li style="list-style:none;">
	        	  		<a class="th radius" href="/company/profile/{{company.id}}/">
                            {% if company.image %}
                                <img src="{{company.image.url}}" />
                            {% else %}
                                {{company.name}}
                            {% endif %}
						</a>
					</li>
				</div>
		    {% endfor %}
		</div>
	    <hr/>
	</div>
{% endblock %}

cetweb/cetweb/templates/company/investor_list.html
{% extends "company/base.html" %}

{% block body %}
	<div class="row">
		<div class="twelve columns">
			<h1 class="header-center">Investor Directory</h1>
		</div>
	</div>
	<div class="row">
		<div style="margin-bottom:20px;" class="twelve columns">
			<hr/>
		    {% for investor in investors %}
			    <div class="three columns">
	        	  	<li style="list-style:none;">
	        	  		<a class="th radius" href="/company/profile/{{company.id}}/">
                            {{investor.name}}
						</a>
					</li>
                    <li style="list-style:none;">
                        Email: {{investor.email}}
                    </li>
                    {% if investor.url %}
                        <li style="list-style:none;">
                            <a href="{{investor.url}}">Website: {{investor.url}}</a>
                        </li>
                    {% endif %}
				</div>
		    {% endfor %}
		</div>
	    <hr/>
	</div>
{% endblock %}

cetweb/cetweb/templates/company/job.html
<h1>Job title: {{job.title}}</h1>
<p>Description: {{job.description}}</p>
<a href="{{job.company.get_absolute_url}}">Company: {{job.company}}</a>

cetweb/cetweb/templates/company/job_form.html
{% extends "company/base.html" %}

{% block body %}
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" />
    </form>
{% endblock %}

cetweb/cetweb/templates/company/job_listing.html
{% extends "company/base.html" %}

{% block body %}
    {% include "company/job.html" %}
{% endblock %}

cetweb/cetweb/templates/company/job_listing_list.html
{% extends "company/base.html" %}

{% block body %}
    {% for job in jobs %}
        {% include "company/job.html" %}
    {% endfor %}
{% endblock %}

cetweb/cetweb/templates/company/mentor_list.html
{% extends "company/base.html" %}

{% block body %}
	<div class="row">
		<div class="twelve columns">
			<h1 class="header-center">Mentor Directory</h1>
		</div>
	</div>
	<div class="row">
		<div style="margin-bottom:20px;" class="twelve columns">
			<hr/>
		    {% for mentor in mentors %}
			    <div class="three columns">
	        	  	<li style="list-style:none;">
	        	  		{{mentor.name}}
	        	  		<!-- <a class="th radius" href="/company/profile/{{company.id}}/">
                            {{mentor.name}}
						</a> -->
					</li>
                    <li style="list-style:none;">
                        Email: {{mentor.email}}
                    </li>
                    {% if mentor.url %}
                        <li style="list-style:none;">
                            LinkedIn:
                            <a href="{{mentor.url}}">{{mentor.url}}</a>
                        </li>
                    {% endif %}
				</div>
		    {% endfor %}
		</div>
	    <hr/>
	</div>
{% endblock %}

cetweb/cetweb/templates/company/profile.html
{% extends "company/base.html" %}
{% load comments %}

{% block body %}
    <h1>Name: {{company.name}}</h1>
    {% if user in company.members.all %}
        <a href="{% url job_create company.pk %}">Create Job Listing</a>
    {% endif %}
    {% for job in company.job_set.all %}
        {% if forloop.first %}
            <h1>Job listings</h1>
        {% endif %}
        <a href="{{job.get_absolute_url}}">{{job.title}}</a>
    {% endfor %}
    <h1>Comments</h1>
    {% get_comment_form for company as form %}
    {% url company_profile company.pk as next %}
    {% include "comments/form.html" %}
    <hr />
    {% render_comment_list for company %}
{% endblock %}

cetweb/cetweb/templates/company/profile2.html
{% extends "base.html" %}
{% load humanize %}

{% block head_title %}{{company.name}}{% endblock %}

{% block body %}
	<div class="row" style="padding-top:15px;">
		<div class="three columns">
            {% if company.image %}
                <div>
                    <a href="{{company.url}}" class="th"><img src="{{company.image.url}}" style="width:100%;"/></a>
                </div>
            {% endif %}
		  	<div>
                <br />
                <a href="{{company.url}}" class="button">Visit Company Site</a>
            </div>
            <div>
                <br />
                {# if user.get_profile in company.profile_set.all #}
                    <a href="{% url company_edit company.pk %}" class="button">Edit Company Page</a>
                {# endif #}
            </div>
		  	<div>
		  		{% if companu.profile_sit.all.count %}
		    	<h5>Team</h5>
		    	<dl>
				  	<dt>Co-Founders</dt>
				  	<dd>
                        {% for founder in company.profile_set.all %}
                            {{founder.user.get_full_name}}<br />
                        {% endfor %}
				  	</dd>
				</dl>
				{% endif %}
		  	</div>
		  	<div>
		    	<h5>Funding</h5>
		    	<p>
                    {{company.investors}}
		    	</p>
		  	</div>
		  	<!-- <div>
		    	<h5>Featured In</h5>
		    	<p>
		    		<a href="http://www.google.com">Techcrunch</a><br />
		    		<a href="http://www.google.com">Crunchies</a><br />
		    		<a href="http://www.google.com">New York Times</a><br />
		    		<a href="http://www.google.com">Forbes</a><br />
		    	</p>
		  	</div> -->
		</div>
		<div class="nine columns" style="border-left:1px solid grey">
			{% if company.video %}
            <iframe width="640" height="360" src="{{company.video}}" frameborder="0" allowfullscreen></iframe>
            {% endif %}
			<h4>About</h4>
            <p>{{company.pitch}}</p>
			{% if company.milestones.count %}
			<h4>Updates</h4>
			<ul class=""
			<h4>Milestones</h4>
			<div class="row">
				<div class="twelve columns">
	                    {% for milestone in company.milestones.all %}
	                        <div class="row">
	                            <div class="four columns">
	                                <blockquote class="milestone">
	                                    <p>{{milestone.title}}
	                                        <cite>{{milestone.date}}</cite>
	                                    </p>
	                                </blockquote>								
	                            </div>
	                            <div class="eight columns">
	                                <div class="panel radius">
	                                    <p>
	                                        {{milestone.description}}
	                                    </p>
	                                </div>
	                            </div>
	                        </div>
	                    {% endfor %}
				</div>
			</div>
            {% endif %}
		</div>
	</div>
{% endblock %}