cetweb/cetweb/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template, redirect_to
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

#project
from cetweb.views import home

urlpatterns = patterns('',
    # Examples:
    #url(r'^$', direct_to_template, {"template":"splash.html"}, name='splash'),
    url(r'^$', home, name='home'),
    url(r'^home/', home, name='home'),
    url(r'^profiles/', include('profiles.urls')),
    url(r'^company/', include('company.urls')),
    url(r'^splash/', include('splash.urls')),
    url(r'^program/', include('program.urls')),
    url(r'^chatroom/', include('chatroom.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^info/', include('info.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/profile/$', redirect_to, {'url': '/profiles/dashboard/'}),
    url(r'^about/$', direct_to_template, {"template":"about.html"}, name='about'),
    url(r'^donate/$', direct_to_template, {"template":"donate.html"}, name='donate'),
    url(r'^faq/$', direct_to_template, {"template":"faq.html"}, name='faq'),
    url(r'^contact/$', direct_to_template, {"template":"contact.html"}, name='contact'),
    url(r'^globalprograms/$', direct_to_template, {"template":"globalprograms.html"}, name='about'),
    url(r'^apply/$', direct_to_template, {"template":"program/apply_reveal.html"}, name='apply'),
    url(r'^comments/', include('django.contrib.comments.urls')),

    # ERROR PAGES
    url(r'^construction/$', direct_to_template, {"template":"errors/construction.html"}, name='construction'),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cetweb/info/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template

urlpatterns = patterns('info.views',
    url(r'^testimonial/create/$', 'testimonial_create', name="testimonial_create"),
)

cetweb/program/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template

urlpatterns = patterns('program.views',
    url(r'^program/(?P<pk>[\w\d]+)/$', 'program_detail', name="program_detail"),
    url(r'^programs/$', 'program_list', name="program_list"),
    url(r'^course/(?P<pk>[\w\d]+)/$', 'course_detail', name="course_detail"),

    url(r'^program/certificate/apply/$', 'program_certificate_apply', name="program_certificate_apply"),
)

cetweb/program/models.py
#standard model stuff
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin

class Program(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="program_images",null=True,blank=True)
    international = models.BooleanField(default=False)

    @models.permalink
    def get_absolute_url(self):
        return ('program_detail', [self.pk])
    def __unicode__(self):
        return self.name

admin.site.register(Program)

class Course(models.Model):
    program = models.ForeignKey(Program)
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="program_images",null=True,blank=True)

    @models.permalink
    def get_absolute_url(self):
        return ('course_detail', [self.pk])
    def __unicode__(self):
        return str(self.program) + ": " + self.name

admin.site.register(Course)

class CETCourse(models.Model):
    name = models.CharField(max_length=300)
    def __unicode__(self):
        return self.name
admin.site.register(CETCourse)

class CertificateApplication(models.Model):
    student_id = models.CharField(max_length=100)
    full_name = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=100)
    email = models.EmailField()
    major = models.CharField(max_length=200)
    courses = models.ManyToManyField(CETCourse,verbose_name="CET courses taken",blank=True)
    address = models.CharField(max_length=200)
    GPA = models.FloatField(blank=False)
    comments = models.TextField(blank=True,null=True)
    def __unicode__(self):
        return self.full_name + ", GPA:" + str(self.GPA)

admin.site.register(CertificateApplication)

cetweb/program/forms.py
from django.forms import ModelForm
from django import forms

from program.models import CertificateApplication
from program.certificate import verify_transcript

class CertificateApplicationForm(ModelForm):
    class Meta:
        model = CertificateApplication

cetweb/cetweb/views.py
#standard django stuff
from django.shortcuts import *
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

#project
from events.models import Event
from info.models import Testimonial

def home(request):
    """
        Displays the job listings.
    """
    context = {
        "events": Event.objects.all(),
        "testimonials": Testimonial.objects.all()
    }
    return render_to_response("home.html",context,context_instance=RequestContext(request))

cetweb/program/views.py
#python
import json

#standard django stuff
from django.shortcuts import *
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt

#project
from program.models import Program, Course
from program.forms import CertificateApplicationForm

def program_list(request):
    programs = Program.objects.all()
    certificate_form = CertificateApplicationForm()
    context = {
        "programs":programs,
        "certificate_form":certificate_form,
    }
    return render_to_response("staticpages/programs.html",context,context_instance=RequestContext(request))

def program_detail(request,pk):
    """
        Displays a course page.
    """
    p = get_object_or_404(Program,pk=pk)
    return render_to_response("program/program.html",{"program":p},context_instance=RequestContext(request))

def course_detail(request,pk):
    """
        Displays a course page.
    """
    c = get_object_or_404(Course,pk=pk)
    return render_to_response("program/course.html",{"course":c},context_instance=RequestContext(request))

@csrf_exempt
def program_certificate_apply(request):
    data = {"success": False,"message":"Please completely fill out the form."}
    form = CertificateApplicationForm(request.POST or request.GET)
    if form.is_valid():
        form.save()
        data['success'] = True
        data['message'] = "Thanks! We will get back to you shortly."
    else:
        data['message'] = str(form.errors)
    return HttpResponse(json.dumps(data), mimetype="application/json")

cetweb/cetweb/templates/program/apply_reveal.html
{% extends "base.html" %}

<div id="apply_reveal" class="reveal-modal">
    <form id="apply_reveal_form" method="post" action="">
        <h3>CET Certificate Program</h3>
        {% csrf_token %}
        {{certificate_form.as_p}}
        <input type="submit" class="nice medium radius blue button close-reveal-modal" id="apply_reveal_button" value="Apply!" />
    </form>
</div>
<script type="text/javascript">
    jQuery(function(){
        jQuery("#apply_reveal_button").click(function(){
            var alert_success = " \
                <div id='certificate_alert' class='alert-box success'> \
                    <div id='certificate_alert_text'>Successfully applied!</div> \
                    <a href='' class='close'>&times;</a> \
                </div> \
            ";
            var alert_error = " \
                <div id='certificate_alert' class='alert-box warning'> \
                    <div id='certificate_alert_text'>Failed to apply!</div> \
                    <a href='' class='close'>&times;</a> \
                </div> \
            ";

            jQuery.ajax({
                type:"POST",
                url:"{% url program_certificate_apply %}", 
                data: $("#apply_reveal_form").serialize(),
                success: function(data){
                    if(data.success==true)
                    {
                        jQuery("#certificate").prepend(alert_success);
                        jQuery("#certificate_alert_text").html(data.message);
                    }
                    else
                    {
                        jQuery("#certificate").prepend(alert_error);
                        jQuery("#certificate_alert_text").html(data.message);
                    }
                    jQuery("html, body").animate({ scrollTop: 0 }, "slow");
                }
            });

            return false;
        });
    });
</script>

cetweb/cetweb/templates/program/course.html
{% extends "program/base.html" %}

{% block body %}
    <h1>Course: {{course.name}}</h1>
{% endblock %}

cetweb/cetweb/templates/program/program.html
<!-- {% extends "program/base.html" %}

{% block body %}
    <h1>Program: {{program.name}}</h1>
    {% for course in program.course_set.all %}
        {% if forloop.first %}
            <h2>Courses</h2>
        {% endif %}
        <h3><a href="{{course.get_absolute_url}}">{{course.name}}</a></h3>
    {% endfor %}
{% endblock %}
 -->

cetweb/cetweb/templates/program/programs.html
{% extends "program/base.html" %}

{% block body %}
    {% for program in programs %}
        <h1><a href="{{program.get_absolute_url}}">Program: {{program.name}}</a></h1>
        {% if not forloop.last %}
            <hr />
        {% endif %}
    {% endfor %}
{% endblock %}